### ISSUE TITLE
An webpack error occurred

### ISSUE THREAD

**Issue by andyyxw** [smooth-code/react-merge-refs#3]
![1](https://user-images.githubusercontent.com/41931722/70970324-0c9f9b00-20d9-11ea-8fee-8a920ef63d3c.png)
![2](https://user-images.githubusercontent.com/41931722/70970328-10332200-20d9-11ea-9ead-65cfeda19a43.png)

I just install and use it normally, I do not know how to fix this error.

**Comment by gregberge** [comment]
Hello @andyyxw did you fix it? If not, please reopen it.
